---
name: Bash Validation
description: Lints Bash scripts
runs:
  using: "composite"
  steps:
    - name: Bash check
      shell: bash
      run: |
        python3 "${{ github.action_path }}/bash_check.py"
