---
name: Laravel/PHP Validation
description: Runs tests for Laravel and PHP projects
runs:
  using: "composite"
  steps:
    - name: Laravel check
      shell: bash
      run: |
        python3 "${{ github.action_path }}/laravel_check.py"
