---
name: Rust Validation
description: Runs tests for Rust projects
runs:
  using: "composite"
  steps:
    - name: Rust check
      shell: bash
      run: |
        python3 "${{ github.action_path }}/rust_check.py"
