---
name: Node.js Validation
description: Runs build scripts for Node.js projects
runs:
  using: "composite"
  steps:
    - name: Node check
      shell: bash
      run: |
        python3 "${{ github.action_path }}/node_check.py"
