---
name: Python Validation
description: Runs tests for Python projects
runs:
  using: "composite"
  steps:
    - name: Python check
      shell: bash
      run: |
        python3 "${{ github.action_path }}/python_check.py"
