---
name: Makefile Validation
description: Runs tests for C/Makefile projects
runs:
  using: "composite"
  steps:
    - name: Makefile check
      shell: bash
      run: |
        python3 "${{ github.action_path }}/makefile_check.py"
