---
name: Dart/Flutter Validation
description: Runs tests for Dart and Flutter projects
runs:
  using: "composite"
  steps:
    - name: Dart check
      shell: bash
      run: |
        python3 "${{ github.action_path }}/dart_check.py"
